# Most of the initial part of the script was derived from - https://github.com/TheComputerGuy96/Magisk/blob/travisci-dev/.travis.yml
language: android

dist: trusty
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools

before_script:
  - sleep 3; echo "y" | sdkmanager --update
  - (while true; do echo "y"; sleep 3; done) | sdkmanager "build-tools;27.0.0" "extras;android;m2repository" "ndk-bundle" > /dev/null
  # New PPA for python for Ubuntu.
  - echo | sudo add-apt-repository ppa:deadsnakes/ppa
  # Required to get PPA going.
  - sudo apt-get update
  - sudo apt-get upgrade
  # Finally, actually install it.
  - sudo apt-get install -y python3.6

env:
  global:
    - GH_EMAIL="you@example.com"
    - GH_USERNAME=YourName
    - ANDROID_HOME=/usr/local/android-sdk
    - PATH=/usr/local/android-sdk/ndk-bundle:${PATH}
    - MAGISK_VER_INTEGER=1640
    - MAGISK_VER_STRING=16.4
    - MAGISK_TIME=$(date -u +%H%M%S)

script:
  # Repo is required to pull Magisk Manager without any errors using kantjer's repository XML.
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  # Get the latest commits via kantjer's XML as cloning the Magisk repo using git always ends with an error due to non-existant commits.
  - cd
  - repo init -u https://github.com/kantjer/magisk_manifest --depth=1
  - repo sync
  - cd Magisk
  # One has to cd into the directory and run from there as opposed to being called from another directory.
  - time python3.6 build.py all ${MAGISK_VER_STRING} ${MAGISK_VER_INTEGER} && echo "Magisk has been successfully built"
  # Finally, upload the files
  - cd
  - cd Magisk
  - cd out
  - |
    for file in *.{zip,apk}
    do
      curl --upload-file "$file" https://transfer.sh/"$file"
      echo
    done

notifications:
  email: false