# Most of the initial part of the script was taken from - https://github.com/TheComputerGuy96/Magisk/blob/travisci-dev/.travis.yml
language: android

dist: trusty
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools

before_script:
  - sleep 3; echo "y" | sdkmanager --update
  - (while true; do echo "y"; sleep 3; done) | sdkmanager "build-tools;27.0.0" "extras;android;m2repository" "ndk-bundle" > /dev/null
  - echo | sudo add-apt-repository ppa:jonathonf/python-3.6
  - sudo apt-get update
  - sudo apt-get install -y python3.6
  - sudo apt-get install python-apt

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - GH_EMAIL="tcg96nougat@gmail.com"
    - GH_FULLNAME="DodoGTA GT"
    - GH_MAGISKFILES_REPO=github.com/TheComputerGuy96/MagiskFiles.git
    - GH_USERNAME=TheComputerGuy96
    - MAGISK_DATE=$(date -u +%Y%m%d)
    - MAGISK_VER_INTEGER=1450
    - MAGISK_VER_STRING=14.5
    - MAGISK_TIME=$(date -u +%H%M%S)
    - MAGISK_ZIPFILES=Magisk-*.zip
    - MAGISKFILES_NAME=MagiskFiles
    - PATH=/usr/local/android-sdk/ndk-bundle:${PATH}
    - secure: "ZVXI+c5pdfwqGebBabpoh0iWTHH3RlYNpTkmkI2WBiFuzQjaE+bOBRU4d5enUZ18MmmtwM3/YbqG86poBQszxaEu3it1hdAwawthhn3BEO6iREe/pNZHDs/H6qFuaXJoInjfl+/VljD1ud5kVNL2VoTmtmb1cVy8+80uN5c/SHmkHkezCWjNr2r5zSkMaPEFjM6DjfeqtZ92NmkrVDlMZYW1WT/Nny0s17uYo+70TvTjIpfrvGuYdQp3ThauHGZLr9DQrMa8egRs0cq/h+Q2mWQZk28FTYLqJEWKw8AcK3ejUGhlFreQYE5w6vO+ZfrPTsMlmTA3rQZAly6Zw6SXK0Z3kR4X/oWNXWXWGmXs63Rd+2IvTgekCcO4kOx+PtbQUxiDY6YqVIvWHnG2jv95y9gA2GRAb5LjoKLZAgCuruxaC7+UPHe+MaNS1CUFQ1XMA9VxjqXdNV8QGEN9dQ771TKBIS5WmPjf58PjqZbBTR9Jr4r1HlrE4KKxssajo+3tIlwAvPte1lXO4uCzcf8zc40abGMjx75lEStu0F/9RNfw6167P9WEG5YXAu9pRBO8ghl5vyBqdnju+B1qvqSpod+v9FWLMkzt+mOq0+DKWsdmtfpYdUxf01f6c1imiCicXDVokpy4JHxntU9+yFmqrdqLqrO3z3J0H1IQBkjwPU0="

script:
  # Required to pull Magisk Manager without any errors.
  - sudo apt-get install curl
  - PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  # Get the latest commits via kanter
  - cd
  # - git clone --recurse-submodules https://github.com/topjohnwu/Magisk.git
  # - cd Magisk/app
  # Make sure all submodules work.
  - repo init -u https://github.com/kantjer/magisk_manifest --depth=1
  - repo sync
  - time python3.6 /home/travis/Magisk/build.py all ${MAGISK_VER_STRING} ${MAGISK_VER_INTEGER} && echo "Magisk has been successfully built"
  # Finally, upload the file
  - cd
  - cd Magisk
  - ls -lR | grep "build.py"
  #- curl --upload-file ./hello.txt https://transfer.sh/hello.txt 

notifications:
  email: false