language: android
script:
  - pwd
  - ls -l
  - cd $TRAVIS_BUILD_DIR
  - ls -l
  - cd $JAVA_HOME/bin
  - export randomString=date +%s | sha256sum | base64 | head -c 32
  - >-
    yes "$randomString" | sudo keytool -genkey -v -keystore release_signature.jks
    -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias
notifications:
  email: false
